
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mufidatun Nabilah
 */
public class Frame1 extends javax.swing.JFrame {

    String temp ="";
    Double ti, bt, h1;
    
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        coba = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        knama = new javax.swing.JTextField();
        kideal = new javax.swing.JTextField();
        ktinggi = new javax.swing.JTextField();
        kberat = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 260, 180, 40);

        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 0, 100, 40);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 30, 80, 40);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 80, 40);

        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 120, 80, 40);

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 80, 40);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(270, 210, 100, 40);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(30, 210, 100, 40);

        coba.setText("Coba Lagi");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        getContentPane().add(coba);
        coba.setBounds(150, 210, 100, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 170, 79, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki-Laki");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(250, 170, 90, 30);
        getContentPane().add(knama);
        knama.setBounds(150, 40, 160, 30);

        kideal.setEditable(false);
        getContentPane().add(kideal);
        kideal.setBounds(220, 270, 70, 30);
        getContentPane().add(ktinggi);
        ktinggi.setBounds(150, 80, 70, 30);
        getContentPane().add(kberat);
        kberat.setBounds(150, 120, 70, 30);

        hasil.setEditable(false);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(40, 330, 330, 40);

        saran.setEditable(false);
        saran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saranActionPerformed(evt);
            }
        });
        getContentPane().add(saran);
        saran.setBounds(40, 380, 330, 40);

        jLabel7.setText("Hasil Diagnosa Anda yaitu :]");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 300, 160, 30);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 0, 100, 100);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Proses(){
    ti = Double.parseDouble(ktinggi.getText());
    bt = Double.parseDouble(kberat.getText());
    
    if (jRadioButton1.isSelected()) {
    h1 = (ti - 100) * 1;
    }else if (jRadioButton2.isSelected()){
    h1 = (ti - 104) * 1;
    }
    temp = Double.toString(h1.intValue());
    if (h1<bt) {
    
        kideal.setText(temp);
        hasil.setText ("Maaf" + knama.getText() + ", Sepertinya anda overweight");
        saran.setText ("Banyaklah Berolahraga dan hindari makanan berkolesterol");
    }else if (h1>bt) {
    
        kideal.setText(temp);
        hasil.setText ("Maaf" + knama.getText() + ", Sepertinya anda underweight");
        saran.setText ("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
    }else {
    
        kideal.setText(temp);
        hasil.setText ("Maaf" + knama.getText() + ", berat badan anda sudah cukup");
        saran.setText ("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
    }
    }
    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        if (knama.getText().equals("")||ktinggi.getText().equals("")
                ||kberat.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Data Harus Diisi Semua");
    }
                else if (jRadioButton1.isSelected()||jRadioButton2.isSelected()){
                        try {
                        Proses();
                        }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
                        }
                }
                        else{
                        JOptionPane.showMessageDialog(null,"Radio Button Harus Dipilih");
                        }
    }//GEN-LAST:event_HitungActionPerformed

    private void saranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saranActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
        // TODO add your handling code here:
        knama.setText("");
        ktinggi.setText("");
        kberat.setText("");
        buttonGroup1.clearSelection();
        kideal.setText("");
        hasil.setText("");
        saran.setText("");
    }//GEN-LAST:event_cobaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coba;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField kberat;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables
}
