
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mufidatun Nabilah
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        VolumeBalok = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanjangSisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        VolumeKubus = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PanjangR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        VolumeBola = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(22, 37, 108, 14);
        jPanel1.add(Panjang);
        Panjang.setBounds(148, 30, 193, 29);

        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(345, 37, 24, 14);

        jLabel4.setText("Masukkan Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(22, 77, 108, 14);
        jPanel1.add(Lebar);
        Lebar.setBounds(148, 70, 193, 28);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(345, 77, 24, 14);

        jLabel6.setText("Masukkan Tinggi");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(22, 119, 108, 14);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(148, 112, 193, 29);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(345, 119, 24, 14);

        VolumeBalok.setText("Hitung");
        VolumeBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBalokActionPerformed(evt);
            }
        });
        jPanel1.add(VolumeBalok);
        VolumeBalok.setBounds(148, 152, 95, 23);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 400, 230);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(29, 30, 139, 14);
        jPanel2.add(PanjangSisi);
        PanjangSisi.setBounds(29, 50, 216, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(255, 58, 29, 14);

        VolumeKubus.setText("Volume");
        VolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeKubusActionPerformed(evt);
            }
        });
        jPanel2.add(VolumeKubus);
        VolumeKubus.setBounds(29, 98, 90, 23);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 400, 230);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(26, 32, 130, 14);
        jPanel3.add(PanjangR);
        PanjangR.setBounds(26, 52, 223, 29);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(259, 59, 26, 14);

        VolumeBola.setText("Volume");
        VolumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBolaActionPerformed(evt);
            }
        });
        jPanel3.add(VolumeBola);
        VolumeBola.setBounds(26, 99, 90, 23);

        jPanel7.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 0, 400, 240);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 36, 400, 260);

        jPanel4.setBackground(new java.awt.Color(255, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Penghitung Volume Bangun Ruang");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 333);
    }// </editor-fold>//GEN-END:initComponents

    private void VolumeBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBalokActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
                
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);}
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeBalokActionPerformed

    private void VolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeKubusActionPerformed
        int sisi;
        sisi = Integer.parseInt(PanjangSisi.getText());
        int hasil = sisi*sisi*sisi;
                
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah : "+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);}
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeKubusActionPerformed

    private void VolumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBolaActionPerformed
        float jari2;
        jari2 = Integer.parseInt(PanjangR.getText());
        float hasil = 4/3 * 22/7 * jari2 * jari2 * jari2;
                
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);}
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField PanjangR;
    private javax.swing.JTextField PanjangSisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JToggleButton VolumeBalok;
    private javax.swing.JToggleButton VolumeBola;
    private javax.swing.JToggleButton VolumeKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
